runtime: python312  # Use Python 3.9 (or your version)
entrypoint: gunicorn -b :$8000 name_project.wsgi

instance_class: F2  # Choose machine class (F1 is the smallest)

env_variables:
  DJANGO_SETTINGS_MODULE: "name_project.settings"
  SECRET_KEY: 'django-insecure-fl3s0%l%mk^s8pzuqtf_w@rb*!)+rwz^cb5dk8=q-+el2!vh!u'
  ALLOWED_HOSTS: ".appspot.com"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
