# Generated by Django 5.1.7 on 2025-03-29 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpc',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='vpc_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
