# Generated by Django 4.2.20 on 2025-04-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_app', '0002_vpc_created_at_alter_vpc_vpc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpc',
            old_name='vpc_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vpc',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vpc',
            name='user',
        ),
        migrations.AddField(
            model_name='vpc',
            name='cidr_block',
            field=models.CharField(default='10.0.0.0/16', max_length=255),
        ),
        migrations.AddField(
            model_name='vpc',
            name='igw_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='vpc_id',
            field=models.CharField(max_length=255),
        ),
    ]
