# Generated by Django 4.2.20 on 2025-04-09 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('name_app', '0003_rename_vpc_name_vpc_name_remove_vpc_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpc',
            name='cidr_block',
        ),
        migrations.RemoveField(
            model_name='vpc',
            name='igw_id',
        ),
        migrations.RemoveField(
            model_name='vpc',
            name='name',
        ),
        migrations.AddField(
            model_name='vpc',
            name='availability_zones',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vpc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vpc',
            name='vpc_name',
            field=models.CharField(default='vpc-name', max_length=100),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='vpc_id',
            field=models.CharField(default='vpc-0000000000000', max_length=100),
        ),
    ]
