# Generated by Django 4.2.20 on 2025-04-09 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('name_app', '0004_remove_vpc_cidr_block_remove_vpc_igw_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpc',
            name='availability_zones',
        ),
        migrations.AddField(
            model_name='vpc',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='vpc_id',
            field=models.CharField(default='vpc-id', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='vpc_name',
            field=models.CharField(default='vpc-name', max_length=255),
        ),
    ]
